#!/usr/bin/env python3
"""Generate typed contract artifacts from contracts/ into shared/ (+ frontend copy).

Source of truth: contracts/api.yaml (OpenAPI 3.1).
Outputs (all marked GENERATED — never hand-edit):
  shared/py/findesk_contracts/api_paths.py   — path constants + operation registry
  shared/ts/api-paths.ts                     — same, for TypeScript consumers
  frontend/src/lib/generated/api-paths.ts    — copy for the Next.js app

As request/response schemas land in api.yaml `components`, this generator
grows Pydantic/TS model emission. CI runs it and fails on drift
(.github/workflows/ci.yml `contracts` job).
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "contracts" / "api.yaml"
HTTP_METHODS = {"get", "post", "put", "patch", "delete"}


def const_name(path: str, method: str) -> str:
    clean = (
        path.strip("/")
        .replace("/", "_")
        .replace("{", "")
        .replace("}", "")
        .replace("-", "_")
        .upper()
        or "ROOT"
    )
    return f"{method.upper()}_{clean}"


def load_operations() -> list[dict[str, str]]:
    spec = yaml.safe_load(SPEC.read_text())
    ops = []
    for path, item in spec.get("paths", {}).items():
        for method, op in item.items():
            if method not in HTTP_METHODS:
                continue
            ops.append(
                {
                    "name": const_name(path, method),
                    "method": method.upper(),
                    "path": path,
                    "summary": op.get("summary", ""),
                    "tag": (op.get("tags") or ["untagged"])[0],
                }
            )
    return ops


def gen_python(ops: list[dict[str, str]], digest: str) -> str:
    lines = [
        '"""GENERATED by scripts/gen_contracts.py from contracts/api.yaml — do not edit."""',
        "",
        f'SPEC_DIGEST = "{digest}"',
        'API_PREFIX = "/api/v1"',
        "",
    ]
    for op in ops:
        lines.append(f'{op["name"]} = "{op["path"]}"')
    lines += [
        "",
        "OPERATIONS: dict[str, dict[str, str]] = {",
    ]
    for op in ops:
        lines.append(
            f'    "{op["name"]}": {{"method": "{op["method"]}", "path": "{op["path"]}", '
            f'"tag": "{op["tag"]}", "summary": {op["summary"]!r}}},'
        )
    lines += ["}", ""]
    return "\n".join(lines)


def gen_ts(ops: list[dict[str, str]], digest: str) -> str:
    lines = [
        "// GENERATED by scripts/gen_contracts.py from contracts/api.yaml — do not edit.",
        f'export const SPEC_DIGEST = "{digest}";',
        'export const API_PREFIX = "/api/v1";',
        "",
        "export const apiPaths = {",
    ]
    for op in ops:
        lines.append(f'  {op["name"]}: "{op["path"]}",')
    lines += [
        "} as const;",
        "",
        "export type ApiOperation = keyof typeof apiPaths;",
        "",
        "export const apiOperations: Record<ApiOperation, { method: string; path: string; tag: string }> = {",
    ]
    for op in ops:
        lines.append(
            f'  {op["name"]}: {{ method: "{op["method"]}", path: "{op["path"]}", tag: "{op["tag"]}" }},'
        )
    lines += ["};", ""]
    return "\n".join(lines)


def main() -> int:
    if not SPEC.exists():
        print(f"missing {SPEC}", file=sys.stderr)
        return 1
    digest = hashlib.sha256(SPEC.read_bytes()).hexdigest()[:16]
    ops = load_operations()

    py_pkg = ROOT / "shared" / "py" / "findesk_contracts"
    py_pkg.mkdir(parents=True, exist_ok=True)
    (py_pkg / "__init__.py").write_text(
        '"""GENERATED package — regenerate via `make contracts`."""\n'
        "from findesk_contracts.api_paths import *  # noqa: F401,F403\n"
    )
    (py_pkg / "api_paths.py").write_text(gen_python(ops, digest))

    ts = gen_ts(ops, digest)
    (ROOT / "shared" / "ts").mkdir(parents=True, exist_ok=True)
    (ROOT / "shared" / "ts" / "api-paths.ts").write_text(ts)
    fe_gen = ROOT / "frontend" / "src" / "lib" / "generated"
    fe_gen.mkdir(parents=True, exist_ok=True)
    (fe_gen / "api-paths.ts").write_text(ts)

    print(f"generated {len(ops)} operations (spec digest {digest})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
