"""GENERATED by scripts/gen_contracts.py from contracts/api.yaml — do not edit."""

SPEC_DIGEST = "310217a3f41f48ae"
API_PREFIX = "/api/v1"

POST_AUTH_LOGIN = "/auth/login"
POST_AUTH_REFRESH = "/auth/refresh"
POST_AUTH_LOGOUT = "/auth/logout"
GET_ME = "/me"
POST_TENANTS_TENANT_ID_SWITCH = "/tenants/{tenant_id}/switch"
GET_BOOKS_TRANSACTIONS = "/books/transactions"
POST_BOOKS_IMPORTS = "/books/imports"
POST_BOOKS_IMPORTS_TALLY = "/books/imports/tally"
POST_BOOKS_ONBOARDING = "/books/onboarding"
GET_BOOKS_EXCEPTIONS = "/books/exceptions"
GET_BOOKS_CHART_OF_ACCOUNTS = "/books/chart-of-accounts"
PATCH_BOOKS_TRANSACTIONS_TXN_ID_CATEGORY = "/books/transactions/{txn_id}/category"
GET_REPORTS_MONTH_END = "/reports/month-end"
POST_AGENT_RUNS = "/agent/runs"
GET_AGENT_RUNS = "/agent/runs"
GET_AGENT_RUNS_RUN_ID = "/agent/runs/{run_id}"
GET_AGENT_RUNS_RUN_ID_STREAM = "/agent/runs/{run_id}/stream"
GET_AGENT_HEALTH = "/agent/health"
GET_CONFLICTS = "/conflicts"
POST_CONFLICTS_CONFLICT_ID_RESOLVE = "/conflicts/{conflict_id}/resolve"
GET_ANOMALIES = "/anomalies"
POST_ANOMALIES_ANOMALY_ID_DECIDE = "/anomalies/{anomaly_id}/decide"
GET_APPROVALS = "/approvals"
POST_APPROVALS_APPROVAL_ID_DECIDE = "/approvals/{approval_id}/decide"
GET_FORECAST = "/forecast"
POST_FORECAST_WHATIF = "/forecast/whatif"
POST_RECEIVABLES_INVOICE_ID_PROMISE = "/receivables/{invoice_id}/promise"
GET_RECEIVABLES_RADAR = "/receivables/radar"
POST_BOOKS_COUNTERPARTIES_PARTY_ID_VERIFY_MSME = "/books/counterparties/{party_id}/verify-msme"
GET_PAYABLES_COMPLIANCE = "/payables/compliance"
GET_PAYABLES_PLAN = "/payables/plan"
GET_LEAKS = "/leaks"
POST_LEAKS_SUBSCRIPTION_ID_USAGE = "/leaks/{subscription_id}/usage"
POST_LEAKS_SUBSCRIPTION_ID_ACTION = "/leaks/{subscription_id}/action"
POST_IMS_SYNC = "/ims/sync"
GET_IMS_QUEUE = "/ims/queue"
POST_IMS_RECORDS_RECORD_ID_ACTION = "/ims/records/{record_id}/action"
GET_WC_ACTIONS = "/wc-actions"
POST_WC_ACTIONS_ACTION_ID_REQUEST = "/wc-actions/{action_id}/request"
GET_CLOSE_CHECKLIST = "/close/checklist"
POST_CLOSE_SIGNOFF = "/close/signoff"
GET_CLOSE_PACK = "/close/pack"
GET_DATAROOM_EXPORT = "/dataroom/export"
GET_AUDIT_VERIFY = "/audit/verify"
GET_DATAROOM = "/dataroom"
POST_DATAROOM_SHARE = "/dataroom/share"
GET_DATAROOM_SHARED = "/dataroom/shared"
GET_WHY_ENTITY_TYPE_ENTITY_ID = "/why/{entity_type}/{entity_id}"

OPERATIONS: dict[str, dict[str, str]] = {
    "POST_AUTH_LOGIN": {"method": "POST", "path": "/auth/login", "tag": "auth", "summary": 'Email+password login (optional TOTP step-up)'},
    "POST_AUTH_REFRESH": {"method": "POST", "path": "/auth/refresh", "tag": "auth", "summary": 'Rotate refresh token — presented jti is revoked, new pair minted (B1); rate-limited'},
    "POST_AUTH_LOGOUT": {"method": "POST", "path": "/auth/logout", "tag": "auth", "summary": "Revoke a refresh token's jti server-side (idempotent)"},
    "GET_ME": {"method": "GET", "path": "/me", "tag": "auth", "summary": 'Current user + memberships'},
    "POST_TENANTS_TENANT_ID_SWITCH": {"method": "POST", "path": "/tenants/{tenant_id}/switch", "tag": "auth", "summary": 'Switch active tenant (CA console)'},
    "GET_BOOKS_TRANSACTIONS": {"method": "GET", "path": "/books/transactions", "tag": "books", "summary": 'Normalized bank feed (cursor paginated)'},
    "POST_BOOKS_IMPORTS": {"method": "POST", "path": "/books/imports", "tag": "books", "summary": 'Upload statement/export file → 202 + run_id'},
    "POST_BOOKS_IMPORTS_TALLY": {"method": "POST", "path": "/books/imports/tally", "tag": "books", "summary": 'Pull outstanding receivables+payables through the Tally HTTP-XML connector (fixture or live mode; mode echoed in the response)'},
    "POST_BOOKS_ONBOARDING": {"method": "POST", "path": "/books/onboarding", "tag": "books", "summary": 'A1 onboarding — import Tally/Zoho invoice export; seeds payment history into memory'},
    "GET_BOOKS_EXCEPTIONS": {"method": "GET", "path": "/books/exceptions", "tag": "books", "summary": 'Unmatched residuals queue'},
    "GET_BOOKS_CHART_OF_ACCOUNTS": {"method": "GET", "path": "/books/chart-of-accounts", "tag": "books", "summary": 'Tenant chart of accounts'},
    "PATCH_BOOKS_TRANSACTIONS_TXN_ID_CATEGORY": {"method": "PATCH", "path": "/books/transactions/{txn_id}/category", "tag": "books", "summary": 'Human category correction — also writes a vendor_category memory claim'},
    "GET_REPORTS_MONTH_END": {"method": "GET", "path": "/reports/month-end", "tag": "books", "summary": 'Month-end pack for a period'},
    "POST_AGENT_RUNS": {"method": "POST", "path": "/agent/runs", "tag": "agent", "summary": 'Start a graph run (kind + params) → run_id'},
    "GET_AGENT_RUNS": {"method": "GET", "path": "/agent/runs", "tag": "agent", "summary": 'List runs'},
    "GET_AGENT_RUNS_RUN_ID": {"method": "GET", "path": "/agent/runs/{run_id}", "tag": "agent", "summary": 'Run status + steps'},
    "GET_AGENT_RUNS_RUN_ID_STREAM": {"method": "GET", "path": "/agent/runs/{run_id}/stream", "tag": "agent", "summary": 'SSE stream of run events (shapes in contracts/events.md)'},
    "GET_AGENT_HEALTH": {"method": "GET", "path": "/agent/health", "tag": "agent", "summary": 'Live subsystem health — worker consumer liveness + memory-engine reachability'},
    "GET_CONFLICTS": {"method": "GET", "path": "/conflicts", "tag": "conflicts", "summary": 'Conflict cards (filter by status)'},
    "POST_CONFLICTS_CONFLICT_ID_RESOLVE": {"method": "POST", "path": "/conflicts/{conflict_id}/resolve", "tag": "conflicts", "summary": 'One-tap resolution (winning claim + rationale)'},
    "GET_ANOMALIES": {"method": "GET", "path": "/anomalies", "tag": "anomalies", "summary": 'Anomaly cards'},
    "POST_ANOMALIES_ANOMALY_ID_DECIDE": {"method": "POST", "path": "/anomalies/{anomaly_id}/decide", "tag": "anomalies", "summary": 'accept | dismiss | mark recovered'},
    "GET_APPROVALS": {"method": "GET", "path": "/approvals", "tag": "approvals", "summary": 'Approval queue'},
    "POST_APPROVALS_APPROVAL_ID_DECIDE": {"method": "POST", "path": "/approvals/{approval_id}/decide", "tag": "approvals", "summary": 'Approve/reject; on approve mints single-use action token and resumes the run'},
    "GET_FORECAST": {"method": "GET", "path": "/forecast", "tag": "cash", "summary": 'Latest forecast (scenarios + lines + drivers)'},
    "POST_FORECAST_WHATIF": {"method": "POST", "path": "/forecast/whatif", "tag": "cash", "summary": 'Deterministic what-if on the stored base scenario (collection delay, inflow haircut, extra outflow) — server computes, UI only renders'},
    "POST_RECEIVABLES_INVOICE_ID_PROMISE": {"method": "POST", "path": "/receivables/{invoice_id}/promise", "tag": "cash", "summary": "Log a client's promise-to-pay; settlement classifies kept/broken deterministically when recon marks the invoice paid (F3 outcome loop)"},
    "GET_RECEIVABLES_RADAR": {"method": "GET", "path": "/receivables/radar", "tag": "cash", "summary": '45-day clocks, accrued interest, escalation states'},
    "POST_BOOKS_COUNTERPARTIES_PARTY_ID_VERIFY_MSME": {"method": "POST", "path": "/books/counterparties/{party_id}/verify-msme", "tag": "books", "summary": "Verify a vendor's Udyam URN (fixture register today) — verified category then scopes §15/43B(h); tag kept alongside, disagreement = drift alert"},
    "GET_PAYABLES_COMPLIANCE": {"method": "GET", "path": "/payables/compliance", "tag": "cash", "summary": 'Buyer-side MSE payables — §15 clock, §16 interest owed, 43B(h) disallowance exposure per open bill'},
    "GET_PAYABLES_PLAN": {"method": "GET", "path": "/payables/plan", "tag": "cash", "summary": 'Deduction Defense — deterministic ranked pay-first plan (closing windows by deadline, breached by daily §16 bleed), cash-aware via latest forecast'},
    "GET_LEAKS": {"method": "GET", "path": "/leaks", "tag": "leaks", "summary": 'LeakRadar table — recurring vendor series with cadence, silent price drift, leak score (0-100) + components, recoverable rupees per year, and category-wise annualized cost; excluded commitments (rent/payroll/EMI) are listed at score 0'},
    "POST_LEAKS_SUBSCRIPTION_ID_USAGE": {"method": "POST", "path": "/leaks/{subscription_id}/usage", "tag": "leaks", "summary": 'Record whether the user still uses a subscription — the one leak signal bank data cannot produce; written to Recall as a decaying belief and picked up by the next scan'},
    "POST_LEAKS_SUBSCRIPTION_ID_ACTION": {"method": "POST", "path": "/leaks/{subscription_id}/action", "tag": "leaks", "summary": 'Queue a cancel/renegotiate/downgrade vendor email for maker-checker approval using the draft the scan wrote; never sends (⚠ consequential — send happens in decide_approval with a single-use token)'},
    "POST_IMS_SYNC": {"method": "POST", "path": "/ims/sync", "tag": "ims", "summary": "Pull the tenant's IMS queue (fixture GSP today) and re-run the deterministic 3-way match + recommendation; decided states are terminal for sync"},
    "GET_IMS_QUEUE": {"method": "GET", "path": "/ims/queue", "tag": "ims", "summary": 'IMS triage queue — records with match tier / recommendation / evidence note, ITC-at-stake totals, and the deemed-acceptance clock (per-record deemed_accept_at/days_remaining/urgency + a queue rollup: next_deadline, itc_at_risk_paise, itc_lapsed_paise, lapsing_soon_paise)'},
    "POST_IMS_RECORDS_RECORD_ID_ACTION": {"method": "POST", "path": "/ims/records/{record_id}/action", "tag": "ims", "summary": 'Request accept/reject on one record — queues a maker-checker approval; execution only via decide with a minted token (never direct)'},
    "GET_WC_ACTIONS": {"method": "GET", "path": "/wc-actions", "tag": "cash", "summary": 'Ranked working-capital options'},
    "POST_WC_ACTIONS_ACTION_ID_REQUEST": {"method": "POST", "path": "/wc-actions/{action_id}/request", "tag": "cash", "summary": 'Move a proposed action into the approval queue (treds only; collect routes via collections)'},
    "GET_CLOSE_CHECKLIST": {"method": "GET", "path": "/close/checklist", "tag": "close", "summary": 'Month-end close checklist — evidence-linked composition over existing engines (recon, conflicts, anomalies, §15 clocks, MSME drift, IMS, forecast freshness, audit chain); blockers vs warnings'},
    "POST_CLOSE_SIGNOFF": {"method": "POST", "path": "/close/signoff", "tag": "close", "summary": 'Maker-checker close sign-off — 409 while blocked; warnings require a rationale; the close record is an audit-chain entry (close.signoff)'},
    "GET_CLOSE_PACK": {"method": "GET", "path": "/close/pack", "tag": "close", "summary": 'Close pack zip = credit pack + close_checklist.md — deterministic, regenerate-and-diff'},
    "GET_DATAROOM_EXPORT": {"method": "GET", "path": "/dataroom/export", "tag": "trust", "summary": 'Credit pack zip — summary.md (score + audit head hash) + receivables/payables/forecast CSVs, all deterministic'},
    "GET_AUDIT_VERIFY": {"method": "GET", "path": "/audit/verify", "tag": "trust", "summary": "Recompute the tenant's hash-chained audit log live — {valid, entries, head_hash, broken_at?}"},
    "GET_DATAROOM": {"method": "GET", "path": "/dataroom", "tag": "cash", "summary": 'Credit-ready data room — FinDesk Score + verified evidence'},
    "POST_DATAROOM_SHARE": {"method": "POST", "path": "/dataroom/share", "tag": "cash", "summary": 'Mint an expiring read-only lender share link (owner/CA only)'},
    "GET_DATAROOM_SHARED": {"method": "GET", "path": "/dataroom/shared", "tag": "cash", "summary": 'Lender-facing read-only view (signed share token is the credential)'},
    "GET_WHY_ENTITY_TYPE_ENTITY_ID": {"method": "GET", "path": "/why/{entity_type}/{entity_id}", "tag": "why", "summary": 'Composed evidence chain (app provenance + memory why-chain)'},
}
