"""GENERATED by scripts/gen_contracts.py from contracts/api.yaml — do not edit."""

SPEC_DIGEST = "44fd2a6594f19c94"
API_PREFIX = "/api/v1"

POST_AUTH_LOGIN = "/auth/login"
POST_AUTH_REFRESH = "/auth/refresh"
GET_ME = "/me"
POST_TENANTS_TENANT_ID_SWITCH = "/tenants/{tenant_id}/switch"
GET_BOOKS_TRANSACTIONS = "/books/transactions"
POST_BOOKS_IMPORTS = "/books/imports"
GET_BOOKS_EXCEPTIONS = "/books/exceptions"
GET_REPORTS_MONTH_END = "/reports/month-end"
POST_AGENT_RUNS = "/agent/runs"
GET_AGENT_RUNS = "/agent/runs"
GET_AGENT_RUNS_RUN_ID = "/agent/runs/{run_id}"
GET_AGENT_RUNS_RUN_ID_STREAM = "/agent/runs/{run_id}/stream"
POST_AGENT_RUNS_RUN_ID_CANCEL = "/agent/runs/{run_id}/cancel"
GET_CONFLICTS = "/conflicts"
POST_CONFLICTS_CONFLICT_ID_RESOLVE = "/conflicts/{conflict_id}/resolve"
GET_ANOMALIES = "/anomalies"
POST_ANOMALIES_ANOMALY_ID_DECIDE = "/anomalies/{anomaly_id}/decide"
GET_APPROVALS = "/approvals"
POST_APPROVALS_APPROVAL_ID_DECIDE = "/approvals/{approval_id}/decide"
GET_FORECAST = "/forecast"
GET_RECEIVABLES_RADAR = "/receivables/radar"
GET_WC_ACTIONS = "/wc-actions"
GET_WHY_ENTITY_TYPE_ENTITY_ID = "/why/{entity_type}/{entity_id}"
POST_WEBHOOKS_AA_CONSENT = "/webhooks/aa/consent"
POST_WEBHOOKS_EMAIL_EVENTS = "/webhooks/email/events"

OPERATIONS: dict[str, dict[str, str]] = {
    "POST_AUTH_LOGIN": {"method": "POST", "path": "/auth/login", "tag": "auth", "summary": 'Email+password login (optional TOTP step-up)'},
    "POST_AUTH_REFRESH": {"method": "POST", "path": "/auth/refresh", "tag": "auth", "summary": 'Rotate refresh token'},
    "GET_ME": {"method": "GET", "path": "/me", "tag": "auth", "summary": 'Current user + memberships'},
    "POST_TENANTS_TENANT_ID_SWITCH": {"method": "POST", "path": "/tenants/{tenant_id}/switch", "tag": "auth", "summary": 'Switch active tenant (CA console)'},
    "GET_BOOKS_TRANSACTIONS": {"method": "GET", "path": "/books/transactions", "tag": "books", "summary": 'Normalized bank feed (cursor paginated)'},
    "POST_BOOKS_IMPORTS": {"method": "POST", "path": "/books/imports", "tag": "books", "summary": 'Upload statement/export file → 202 + run_id'},
    "GET_BOOKS_EXCEPTIONS": {"method": "GET", "path": "/books/exceptions", "tag": "books", "summary": 'Unmatched residuals queue'},
    "GET_REPORTS_MONTH_END": {"method": "GET", "path": "/reports/month-end", "tag": "books", "summary": 'Month-end pack for a period'},
    "POST_AGENT_RUNS": {"method": "POST", "path": "/agent/runs", "tag": "agent", "summary": 'Start a graph run (kind + params) → run_id'},
    "GET_AGENT_RUNS": {"method": "GET", "path": "/agent/runs", "tag": "agent", "summary": 'List runs'},
    "GET_AGENT_RUNS_RUN_ID": {"method": "GET", "path": "/agent/runs/{run_id}", "tag": "agent", "summary": 'Run status + steps'},
    "GET_AGENT_RUNS_RUN_ID_STREAM": {"method": "GET", "path": "/agent/runs/{run_id}/stream", "tag": "agent", "summary": 'SSE stream of run events (shapes in contracts/events.md)'},
    "POST_AGENT_RUNS_RUN_ID_CANCEL": {"method": "POST", "path": "/agent/runs/{run_id}/cancel", "tag": "agent", "summary": 'Cancel a run'},
    "GET_CONFLICTS": {"method": "GET", "path": "/conflicts", "tag": "conflicts", "summary": 'Conflict cards (filter by status)'},
    "POST_CONFLICTS_CONFLICT_ID_RESOLVE": {"method": "POST", "path": "/conflicts/{conflict_id}/resolve", "tag": "conflicts", "summary": 'One-tap resolution (winning claim + rationale)'},
    "GET_ANOMALIES": {"method": "GET", "path": "/anomalies", "tag": "anomalies", "summary": 'Anomaly cards'},
    "POST_ANOMALIES_ANOMALY_ID_DECIDE": {"method": "POST", "path": "/anomalies/{anomaly_id}/decide", "tag": "anomalies", "summary": 'accept | dismiss | mark recovered'},
    "GET_APPROVALS": {"method": "GET", "path": "/approvals", "tag": "approvals", "summary": 'Approval queue'},
    "POST_APPROVALS_APPROVAL_ID_DECIDE": {"method": "POST", "path": "/approvals/{approval_id}/decide", "tag": "approvals", "summary": 'Approve/reject; on approve mints single-use action token and resumes the run'},
    "GET_FORECAST": {"method": "GET", "path": "/forecast", "tag": "cash", "summary": 'Latest forecast (scenarios + lines + drivers)'},
    "GET_RECEIVABLES_RADAR": {"method": "GET", "path": "/receivables/radar", "tag": "cash", "summary": '45-day clocks'},
    "GET_WC_ACTIONS": {"method": "GET", "path": "/wc-actions", "tag": "cash", "summary": 'Ranked working-capital options'},
    "GET_WHY_ENTITY_TYPE_ENTITY_ID": {"method": "GET", "path": "/why/{entity_type}/{entity_id}", "tag": "why", "summary": 'Composed evidence chain (app provenance + memory why-chain)'},
    "POST_WEBHOOKS_AA_CONSENT": {"method": "POST", "path": "/webhooks/aa/consent", "tag": "webhooks", "summary": 'Account Aggregator consent callback (signed)'},
    "POST_WEBHOOKS_EMAIL_EVENTS": {"method": "POST", "path": "/webhooks/email/events", "tag": "webhooks", "summary": 'Email delivery/open/reply events (signed)'},
}
