"""GENERATED by scripts/gen_contracts.py from contracts/api.yaml — do not edit."""

SPEC_DIGEST = "164ba237fe889cfc"
API_PREFIX = "/api/v1"

POST_AUTH_LOGIN = "/auth/login"
POST_AUTH_REFRESH = "/auth/refresh"
GET_ME = "/me"
POST_TENANTS_TENANT_ID_SWITCH = "/tenants/{tenant_id}/switch"
GET_BOOKS_TRANSACTIONS = "/books/transactions"
POST_BOOKS_IMPORTS = "/books/imports"
POST_BOOKS_ONBOARDING = "/books/onboarding"
GET_BOOKS_EXCEPTIONS = "/books/exceptions"
GET_BOOKS_CHART_OF_ACCOUNTS = "/books/chart-of-accounts"
PATCH_BOOKS_TRANSACTIONS_TXN_ID_CATEGORY = "/books/transactions/{txn_id}/category"
GET_REPORTS_MONTH_END = "/reports/month-end"
POST_AGENT_RUNS = "/agent/runs"
GET_AGENT_RUNS = "/agent/runs"
GET_AGENT_RUNS_RUN_ID = "/agent/runs/{run_id}"
GET_AGENT_RUNS_RUN_ID_STREAM = "/agent/runs/{run_id}/stream"
POST_AGENT_RUNS_RUN_ID_CANCEL = "/agent/runs/{run_id}/cancel"
GET_AGENT_HEALTH = "/agent/health"
GET_CONFLICTS = "/conflicts"
POST_CONFLICTS_CONFLICT_ID_RESOLVE = "/conflicts/{conflict_id}/resolve"
GET_ANOMALIES = "/anomalies"
POST_ANOMALIES_ANOMALY_ID_DECIDE = "/anomalies/{anomaly_id}/decide"
GET_APPROVALS = "/approvals"
POST_APPROVALS_APPROVAL_ID_DECIDE = "/approvals/{approval_id}/decide"
GET_FORECAST = "/forecast"
GET_RECEIVABLES_RADAR = "/receivables/radar"
GET_WC_ACTIONS = "/wc-actions"
POST_WC_ACTIONS_ACTION_ID_REQUEST = "/wc-actions/{action_id}/request"
GET_DATAROOM = "/dataroom"
POST_DATAROOM_SHARE = "/dataroom/share"
GET_DATAROOM_SHARED = "/dataroom/shared"
GET_WHY_ENTITY_TYPE_ENTITY_ID = "/why/{entity_type}/{entity_id}"
POST_WEBHOOKS_AA_CONSENT = "/webhooks/aa/consent"
POST_WEBHOOKS_EMAIL_EVENTS = "/webhooks/email/events"

OPERATIONS: dict[str, dict[str, str]] = {
    "POST_AUTH_LOGIN": {"method": "POST", "path": "/auth/login", "tag": "auth", "summary": 'Email+password login (optional TOTP step-up)'},
    "POST_AUTH_REFRESH": {"method": "POST", "path": "/auth/refresh", "tag": "auth", "summary": 'Rotate refresh token'},
    "GET_ME": {"method": "GET", "path": "/me", "tag": "auth", "summary": 'Current user + memberships'},
    "POST_TENANTS_TENANT_ID_SWITCH": {"method": "POST", "path": "/tenants/{tenant_id}/switch", "tag": "auth", "summary": 'Switch active tenant (CA console)'},
    "GET_BOOKS_TRANSACTIONS": {"method": "GET", "path": "/books/transactions", "tag": "books", "summary": 'Normalized bank feed (cursor paginated)'},
    "POST_BOOKS_IMPORTS": {"method": "POST", "path": "/books/imports", "tag": "books", "summary": 'Upload statement/export file → 202 + run_id'},
    "POST_BOOKS_ONBOARDING": {"method": "POST", "path": "/books/onboarding", "tag": "books", "summary": 'A1 onboarding — import Tally/Zoho invoice export; seeds payment history into memory'},
    "GET_BOOKS_EXCEPTIONS": {"method": "GET", "path": "/books/exceptions", "tag": "books", "summary": 'Unmatched residuals queue'},
    "GET_BOOKS_CHART_OF_ACCOUNTS": {"method": "GET", "path": "/books/chart-of-accounts", "tag": "books", "summary": 'Tenant chart of accounts'},
    "PATCH_BOOKS_TRANSACTIONS_TXN_ID_CATEGORY": {"method": "PATCH", "path": "/books/transactions/{txn_id}/category", "tag": "books", "summary": 'Human category correction — also writes a vendor_category memory claim'},
    "GET_REPORTS_MONTH_END": {"method": "GET", "path": "/reports/month-end", "tag": "books", "summary": 'Month-end pack for a period'},
    "POST_AGENT_RUNS": {"method": "POST", "path": "/agent/runs", "tag": "agent", "summary": 'Start a graph run (kind + params) → run_id'},
    "GET_AGENT_RUNS": {"method": "GET", "path": "/agent/runs", "tag": "agent", "summary": 'List runs'},
    "GET_AGENT_RUNS_RUN_ID": {"method": "GET", "path": "/agent/runs/{run_id}", "tag": "agent", "summary": 'Run status + steps'},
    "GET_AGENT_RUNS_RUN_ID_STREAM": {"method": "GET", "path": "/agent/runs/{run_id}/stream", "tag": "agent", "summary": 'SSE stream of run events (shapes in contracts/events.md)'},
    "POST_AGENT_RUNS_RUN_ID_CANCEL": {"method": "POST", "path": "/agent/runs/{run_id}/cancel", "tag": "agent", "summary": 'Cancel a run'},
    "GET_AGENT_HEALTH": {"method": "GET", "path": "/agent/health", "tag": "agent", "summary": 'Live subsystem health — worker consumer liveness + memory-engine reachability'},
    "GET_CONFLICTS": {"method": "GET", "path": "/conflicts", "tag": "conflicts", "summary": 'Conflict cards (filter by status)'},
    "POST_CONFLICTS_CONFLICT_ID_RESOLVE": {"method": "POST", "path": "/conflicts/{conflict_id}/resolve", "tag": "conflicts", "summary": 'One-tap resolution (winning claim + rationale)'},
    "GET_ANOMALIES": {"method": "GET", "path": "/anomalies", "tag": "anomalies", "summary": 'Anomaly cards'},
    "POST_ANOMALIES_ANOMALY_ID_DECIDE": {"method": "POST", "path": "/anomalies/{anomaly_id}/decide", "tag": "anomalies", "summary": 'accept | dismiss | mark recovered'},
    "GET_APPROVALS": {"method": "GET", "path": "/approvals", "tag": "approvals", "summary": 'Approval queue'},
    "POST_APPROVALS_APPROVAL_ID_DECIDE": {"method": "POST", "path": "/approvals/{approval_id}/decide", "tag": "approvals", "summary": 'Approve/reject; on approve mints single-use action token and resumes the run'},
    "GET_FORECAST": {"method": "GET", "path": "/forecast", "tag": "cash", "summary": 'Latest forecast (scenarios + lines + drivers)'},
    "GET_RECEIVABLES_RADAR": {"method": "GET", "path": "/receivables/radar", "tag": "cash", "summary": '45-day clocks, accrued interest, escalation states'},
    "GET_WC_ACTIONS": {"method": "GET", "path": "/wc-actions", "tag": "cash", "summary": 'Ranked working-capital options'},
    "POST_WC_ACTIONS_ACTION_ID_REQUEST": {"method": "POST", "path": "/wc-actions/{action_id}/request", "tag": "cash", "summary": 'Move a proposed action into the approval queue (treds only; collect routes via collections)'},
    "GET_DATAROOM": {"method": "GET", "path": "/dataroom", "tag": "cash", "summary": 'Credit-ready data room — FinDesk Score + verified evidence'},
    "POST_DATAROOM_SHARE": {"method": "POST", "path": "/dataroom/share", "tag": "cash", "summary": 'Mint an expiring read-only lender share link (owner/CA only)'},
    "GET_DATAROOM_SHARED": {"method": "GET", "path": "/dataroom/shared", "tag": "cash", "summary": 'Lender-facing read-only view (signed share token is the credential)'},
    "GET_WHY_ENTITY_TYPE_ENTITY_ID": {"method": "GET", "path": "/why/{entity_type}/{entity_id}", "tag": "why", "summary": 'Composed evidence chain (app provenance + memory why-chain)'},
    "POST_WEBHOOKS_AA_CONSENT": {"method": "POST", "path": "/webhooks/aa/consent", "tag": "webhooks", "summary": 'Account Aggregator consent callback (signed)'},
    "POST_WEBHOOKS_EMAIL_EVENTS": {"method": "POST", "path": "/webhooks/email/events", "tag": "webhooks", "summary": 'Email delivery/open/reply events (signed)'},
}
